apiVersion: v1
kind: Pod
metadata:
  name: mongodb
  labels:
    role: myrole
spec:
  containers:
    - name: database
      image: mongo
      ports:
        - name: web
          containerPort: 80
          protocol: TCP
  